database.c File Reference
#include <sys/types.h>
#include <string.h>
#include <db.h>
#include <glib.h>
#include `database.h`
#include `util.h`
#include `error.h`
Data Structures
struct ADatabaseHandle
Functions
DB * getDatabaseP (const char *category, const char *subcategory, gboolean writeable)
DB * openDatabase (const char *category, const char *subcategory, gboolean needWrite)
Open a database.
void * luau_db_queryDatabase (const char *category, const char *subcategory, const char *key)
Database query.
gboolean luau_db_keyExists (const char *category, const char *subcategory, const char *key)
Check for key existence.
gboolean luau_db_create (const char *category, const char *subcategory)
GPtrArray * luau_db_getAllDBKeys (const char *category, const char *subcategory)
Get an array of all keys in the database.
gboolean luau_db_setValue (const char *category, const char *subcategory, const char *key, const void *value, size_t size)
Set a key/value pair in the database.
gboolean luau_db_setValueString (const char *category, const char *subcategory, const char *key, const char *string)
Set a key/value pair where the value is a string.
gboolean luau_db_setValueInt (const char *category, const char *subcategory, const char *key, int value)
Set a key/value pair where the value is an integer.
gboolean luau_db_deleteKey (const char *category, const char *subcategory, const char *key)
Delete a key/value pair in the specified database.
gboolean luau_db_clear (const char *category, const char *subcategory)
Clear a database of all keys.
void luau_db_keepOpen (gboolean yesOrNo)
Keep all opened databases open to speed up multiple database operations.
void luau_db_closeAll (void)
Close all open databases.
Variables
gboolean keepOpen = FALSE
GPtrArray * dbPs = NULL
Function Documentation
DB * getDatabaseP (const char * category, const char * subcategory, gboolean writeable) [static]
Definition at line 326 of file database.c.
References curr, dbPs, DBUGOUT, AUpdate::id, keepOpen, lutil_streq(), lutil_vstrcreate(), and openDatabase().
Referenced by luau_db_clear(), luau_db_create(), luau_db_deleteKey(), luau_db_getAllDBKeys(), luau_db_queryDatabase(), and luau_db_setValue().
gboolean luau_db_clear (const char * category, const char * subcategory)
Clear a database of all keys.
Definition at line 278 of file database.c.
References DB_DIR, ERROR, getDatabaseP(), and lutil_vstrcreate().
void luau_db_closeAll (void)
Close all open databases.
Definition at line 300 of file database.c.
References curr, dbPs, DBUGOUT, and AUpdate::id.
Referenced by luau_closeAllDatabases().
gboolean luau_db_create (const char * category, const char * subcategory)
Definition at line 112 of file database.c.
References getDatabaseP(), and keepOpen.
Referenced by main().
gboolean luau_db_deleteKey (const char * category, const char * subcategory, const char * key)
Delete a key/value pair in the specified database.
Definition at line 259 of file database.c.
References ERROR, and getDatabaseP().
Referenced by luau_deleteApp().
GPtrArray* luau_db_getAllDBKeys (const char * category, const char * subcategory)
Get an array of all keys in the database.
Get all the keys in the specified database using libdb's 'cursor' interface. Returns NULL on error.
category is the main category where the key is stored (actually the database filename)
subcategory is the sub category where the key is stored (actually the database name)
Returns: a GPtrArray of all the keys in specified database (must be free'd), or NULL on failure.
Definition at line 138 of file database.c.
References ERROR, getDatabaseP(), and keepOpen.
Referenced by luau_getAllPrograms().
void luau_db_keepOpen (gboolean yesOrNo)
Keep all opened databases open to speed up multiple database operations.
Definition at line 295 of file database.c.
References keepOpen.
Referenced by luau_keepDatabasesOpen().
gboolean luau_db_keyExists (const char * category, const char * subcategory, const char * key)
Check for key existence.
Find if a key exists in the specified database. Note that this will also return FALSE if the database doesn't exist, or there is an error in opening it.
category is the main category where the key is stored (actually the database filename)
subcategory is the sub category where the key is stored (actually the database name)
key is the name of the key we want to see exists
Returns: TRUE if the key exists, FALSE otherwise
Definition at line 107 of file database.c.
References luau_db_queryDatabase().
void* luau_db_queryDatabase (const char * category, const char * subcategory, const char * key)
Database query.
Query for the value associated with the given key. Returns NULL if the query failed, or if there's no such key in the database.
category is the main category where the key is stored (actually the database filename)
subcategory is the sub category where the key is stored (actually the database name)
key is the name of the key we want to find the data for (we only support strings as keys)
Returns: the associated data (must be free'd), or NULL otherwise
Definition at line 65 of file database.c.
References ERROR, getDatabaseP(), and keepOpen.
Referenced by isHidden(), luau_db_keyExists(), and luau_getProgInfo().
gboolean luau_db_setValue (const char * category, const char * subcategory, const char * key, const void * value, size_t size)
Set a key/value pair in the database.
Set the value of key to value in the category.subcategory database. Overwrites previous value if one exists, or creates a new pair otherwise. size must contain the size (in bytes) of value.
category is the main category where the key is stored (actually the database filename)
subcategory is the sub category where the key is stored (actually the database name)
key is the name of the key we want to set/change
value is the new value
size is the size of the new value (in bytes)
See also: luau_db_setValueString
luau_db_setValueInt
Definition at line 190 of file database.c.
References ERROR, getDatabaseP(), keepOpen, and size.
Referenced by luau_db_setValueInt(), and luau_db_setValueString().
gboolean luau_db_setValueInt (const char * category, const char * subcategory, const char * key, int value)
Set a key/value pair where the value is an integer.
Front-end to luau_db_setValue for setting string values in the database. Otherwise works the same as luau_db_setValue.
category is the main category where the key is stored (actually the database filename)
subcategory is the sub category where the key is stored (actually the database name)
key is the name of the key we want to set/change
value is the new value
See also: luau_db_setValue
Definition at line 253 of file database.c.
References DBUGOUT, and luau_db_setValue().
Referenced by luau_hideUpdate(), luau_registerNewApp(), and luau_unhideUpdate().
gboolean luau_db_setValueString (const char * category, const char * subcategory, const char * key, const char * string)
Set a key/value pair where the value is a string.
Front-end to luau_db_setValue for setting string values in the database. Otherwise works the same as luau_db_setValue.
category is the main category where the key is stored (actually the database filename)
subcategory is the sub category where the key is stored (actually the database name)
key is the name of the key we want to set/change
value is the new value
See also: luau_db_setValue
Definition at line 233 of file database.c.
References DBUGOUT, and luau_db_setValue().
Referenced by luau_registerNewApp().
DB * openDatabase (const char * category, const char * subcategory, gboolean needWrite) [static]
Open a database.
Open and return a DB pointer for the given database. Returns NULL on error. *
category is the main category where the key is stored (actually the database filename)
subcategory is the sub category where the key is stored (actually the database name)
needWrite specifies whether we need write permissions
Returns: a DB pointer for the database (must be closed when finished), or NULL if operation fails
Definition at line 414 of file database.c.
References DB_DIR, DBUGOUT, ERROR, and lutil_vstrcreate().
Referenced by getDatabaseP().
Variable Documentation
GPtrArray* dbPs = NULL
Definition at line 49 of file database.c.
Referenced by getDatabaseP(), and luau_db_closeAll().
gboolean keepOpen = FALSE
Definition at line 48 of file database.c.
Referenced by getDatabaseP(), luau_db_create(), luau_db_getAllDBKeys(), luau_db_keepOpen(), luau_db_queryDatabase(), and luau_db_setValue().