error.c File Reference
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <glib.h>
#include `util.h`
#include `error.h`
Defines
#define G_LOG_DOMAIN `Luau`
Functions
int defaultPromptFunc (const char *title, const char *msg, int nTotal, int nDefault, const char *choice1, va_list args)
void lutil_error_setPromptFunc (UPromptFunc promptFunc)
Set a new function to prompt the user with.
void lutil_error_resetPromptFunc (void)
Reset the prompt function to the default prompt function.
void lutil_error_fatal (const char *filename, const char *function, int lineno, const char *template,...)
int lutil_error_prompt (const char *title, const char *msg, int nTotal, int nDefault, const char *choice1,...)
Prompt the user for input.
void lutil_error (const char *filename, const char *function, int lineno, const char *template,...)
void lutil_debug (const char *filename, const char *function, int lineno, const char *template,...)
Variables
UPromptFunc promptFunc_global = defaultPromptFunc
Define Documentation
#define G_LOG_DOMAIN `Luau`
Definition at line 42 of file error.c.
Referenced by lutil_debug().
Function Documentation
int defaultPromptFunc (const char * title, const char * msg, int nTotal, int nDefault, const char * choice1, va_list args) [static]
Definition at line 216 of file error.c.
Referenced by lutil_error_resetPromptFunc().
void lutil_debug (const char * filename, const char * function, int lineno, const char * template, ...)
Definition at line 192 of file error.c.
References G_LOG_DOMAIN, and lutil_valistToString().
void lutil_error (const char * filename, const char * function, int lineno, const char * template, ...)
Display an error using the defined error function (or the default, if none is defined). Default behavior (as defined by defaultErrorFunc) is to simply display the error to STDERR in the following format:
 *** ERROR ***
 luau: FILENAME: FUNCTION: STRING
filename is the name of the source file where the error occured
function is the name of the function where the error occured
lineno is the line number where the error occured
template is the (printf) template for the error string
... is the arguments to the (printf) template.
Definition at line 173 of file error.c.
References lutil_valistToString().
void lutil_error_fatal (const char * filename, const char * function, int lineno, const char * template, ...)
Display a fatal error message and die. Cannot be overridden. Only called internally when there is a memory failure.
string is the error string
filename is the name of the source file where the error occured
function is the name of the function where the error occured
lineno is the line number where the error occured
Returns: ... Never.
Definition at line 115 of file error.c.
References lutil_valistToString().
int lutil_error_prompt (const char * title, const char * msg, int nTotal, int nDefault, const char * choice1, ...)
Prompt the user for input.
Prompt the user for input, using the defined prompt function (or the default, if none is defined). Default behavior is not to prompt the user at all, but instead to return the default value.
title is the name of the prompt
msg is the prompt to ask the user
nTotal is the number of options given
nDefault is the id of the default option (must be provided)
choice1 is the first choice
args is the rest of the choices
See also: lutil_error_setPromptFunc(p.)
Definition at line 145 of file error.c.
References promptFunc_global.
Referenced by luau_downloadUpdate(), and luau_net_downloadUpdate().
void lutil_error_resetPromptFunc (void)
Reset the prompt function to the default prompt function.
Definition at line 100 of file error.c.
References defaultPromptFunc(), and promptFunc_global.
Referenced by luau_resetPromptFunc().
void lutil_error_setPromptFunc (UPromptFunc promptFunc)
Set a new function to prompt the user with.
Define a new function to be used for prompting the user for input. The default value, specified by nDefault, and the title (title) may be ignored. The prompt function should return the id of the value picked (first = 1, second = 2, etc.). Default behavior is to not prompt the user at all, and simply return the default value.
promptFunc is the new prompting function to use
title is the name of the prompt
msg is the prompt to ask the user
nTotal is the number of options given
nDefault is the id of the default option (must be provided)
choice1 is the first choice
args is the rest of the choices
See also: lutil_error_prompt(p.)
Definition at line 90 of file error.c.
References promptFunc_global.
Referenced by luau_registerPromptFunc().
Variable Documentation
UPromptFunc promptFunc_global = defaultPromptFunc [static]
Definition at line 48 of file error.c.
Referenced by lutil_error_prompt(), lutil_error_resetPromptFunc(), and lutil_error_setPromptFunc().