ftp.h File Reference
URL retrieving subroutines.
#include <glib.h>
Typedefs
typedef int(* UProgressCallback)(void *clientp, double dltotal, double dlnow, double ultotal, double ulnow)
Functions
gboolean lutil_ftp_downloadToFile (const char *url, const char *downloadTo, GError **err)
GString * lutil_ftp_getURL (const char *url, GError **err)
void lutil_ftp_setCallbackFunc (UProgressCallback callback)
void lutil_ftp_resetCallbackFunc (void)
Detailed Description
URL retrieving subroutines.
Standard interface for downloading files either to the local filesystem or to memory. Note that despite the name of the file `ftp.h`, -any- protocol supported by libcurl is supported here.
Definition in file ftp.h.
Typedef Documentation
typedef int(* UProgressCallback)(void *clientp, double dltotal, double dlnow, double ultotal, double ulnow)
Definition at line 38 of file ftp.h.
Function Documentation
gboolean lutil_ftp_downloadToFile (const char * url, const char * downloadTo, GError ** err)
Definition at line 55 of file ftp.c.
References DBUGOUT, downloadCallback_global, LUTIL_BASE_ERROR, and LUTIL_BASE_ERROR_FAILED.
Referenced by luau_net_downloadUpdate().
GString* lutil_ftp_getURL (const char * url, GError ** err)
Definition at line 98 of file ftp.c.
References callback(), AData::data, DBUGOUT, LUTIL_BASE_ERROR, LUTIL_BASE_ERROR_FAILED, and AData::size.
Referenced by luau_getProgInfoFromXML_url(), and luau_net_queryServer().
void lutil_ftp_resetCallbackFunc (void)
Definition at line 146 of file ftp.c.
References downloadCallback_global.
Referenced by luau_resetProgressCallback().
void lutil_ftp_setCallbackFunc (UProgressCallback callback)
Definition at line 141 of file ftp.c.
References callback(), and downloadCallback_global.
Referenced by luau_registerProgressCallback().