ftp.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <unistd.h>
#include <errno.h>
#include <curl/curl.h>
#include <curl/types.h>
#include <curl/easy.h>
#include <glib.h>
#include `ftp.h`
#include `util.h`
#include `error.h`
Data Structures
struct AData
Describe a chunk of data.
Functions
size_t callback (void *ptr, size_t size, size_t nmemb, void *data)
gboolean lutil_ftp_downloadToFile (const char *url, const char *downloadTo, GError **err)
GString * lutil_ftp_getURL (const char *url, GError **err)
void lutil_ftp_setCallbackFunc (UProgressCallback callback)
void lutil_ftp_resetCallbackFunc (void)
Variables
UProgressCallback downloadCallback_global = NULL
Function Documentation
size_t callback (void * ptr, size_t size, size_t nmemb, void * data) [static]
Definition at line 153 of file ftp.c.
References AData::data, and AData::size.
Referenced by lutil_ftp_getURL(), and lutil_ftp_setCallbackFunc().
gboolean lutil_ftp_downloadToFile (const char * url, const char * downloadTo, GError ** err)
Definition at line 55 of file ftp.c.
References DBUGOUT, downloadCallback_global, LUTIL_BASE_ERROR, and LUTIL_BASE_ERROR_FAILED.
Referenced by luau_net_downloadUpdate().
GString* lutil_ftp_getURL (const char * url, GError ** err)
Definition at line 98 of file ftp.c.
References callback(), AData::data, DBUGOUT, LUTIL_BASE_ERROR, LUTIL_BASE_ERROR_FAILED, and AData::size.
Referenced by luau_getProgInfoFromXML_url(), and luau_net_queryServer().
void lutil_ftp_resetCallbackFunc (void)
Definition at line 146 of file ftp.c.
References downloadCallback_global.
Referenced by luau_resetProgressCallback().
void lutil_ftp_setCallbackFunc (UProgressCallback callback)
Definition at line 141 of file ftp.c.
References callback(), and downloadCallback_global.
Referenced by luau_registerProgressCallback().
Variable Documentation
UProgressCallback downloadCallback_global = NULL [static]
Definition at line 50 of file ftp.c.
Referenced by lutil_ftp_downloadToFile(), lutil_ftp_resetCallbackFunc(), and lutil_ftp_setCallbackFunc().