gcontainer.h File Reference
#include <glib.h>
Data Structures
struct GContainer
Generic wrapper around glib Pointer Array and Doubly/Singly Linked List objects.
struct GIterator
An Iterator over a GContainer(p.) object.
Enumerations
enum GContType { GCONT_PTR_ARRAY,
GCONT_LIST,
GCONT_SLIST
 }
Describe a generic glib container type.
Functions
GContainer * g_container_new (GContType type)
GContainer * g_container_new_from_data (GContType type, void *data)
GContainer * g_container_dup (const GContainer *container)
Performs a shallow copy and returns a new GContainer(p.) object.
void g_container_add (GContainer *container, const gpointer data)
void g_container_concat (GContainer *container, const GContainer *new_items)
gboolean g_container_remove (GContainer *container, const gpointer data)
gboolean g_container_remove_fast (GContainer *container, const gpointer data)
gpointer g_container_remove_index (GContainer *container, guint index)
gpointer g_container_remove_index_fast (GContainer *container, guint index)
gpointer g_container_index (const GContainer *container, guint index)
gboolean g_container_get_iter (GIterator *iter, const GContainer *container)
gboolean g_container_get_iter_last (GIterator *iter, const GContainer *container)
gpointer g_iterator_get (const GIterator *iter)
gpointer g_iterator_next (GIterator *iter)
gpointer g_iterator_prev (GIterator *iter)
gboolean g_iterator_hasNext (const GIterator *iter)
gboolean g_iterator_hasPrev (const GIterator *iter)
void * g_container_free (GContainer *container, gboolean freeAssoc)
Free the memory allocated to a GContainer(p.).
void g_container_copy (GContainer *dest, const GContainer *src)
Copy the contents of one GContainer(p.) into another (not overwriting).
void * g_container_convert (GContType type, GContainer *container)
Convert the underlying container type of a GContainer(p.).
void g_container_destroy (GContainer *array)
Free a GContainer(p.) and all the pointers it stores.
void g_container_destroy_type (GContType type, void *array)
Free an array of specified type and all the pointers it stores.
Enumeration Type Documentation
enum GContType
Describe a generic glib container type.
Enumeration values:
GCONT_PTR_ARRAY
GCONT_LIST
GCONT_SLIST
Definition at line 30 of file gcontainer.h.
Function Documentation
void g_container_add (GContainer * container, const gpointer data)
Definition at line 88 of file gcontainer.c.
References GContainer::data, ERROR, GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, GContainer::len, and GContainer::type.
Referenced by addToMirrorList(), appendStringToAttributeList(), g_container_concat(), g_container_convert(), g_container_copy(), lutil_gsplit(), parseMirrorDef(), parseMirrorIDs(), parsePackageProperties(), parsePkgGroup(), parseUpdate(), and setAttributeValue().
void g_container_concat (GContainer * container, const GContainer * new_items)
Definition at line 102 of file gcontainer.c.
References g_container_add(), g_container_get_iter(), g_iterator_hasNext(), and g_iterator_next().
Referenced by getAttributeList(), parseMirrorIDs(), parsePackageAttrMirrors(), and parsePackageProperties().
void* g_container_convert (GContType type, GContainer * container)
Convert the underlying container type of a GContainer(p.).
Definition at line 347 of file gcontainer.c.
References GContainer::data, ERROR, g_container_add(), g_container_free(), g_container_get_iter(), g_container_new(), g_iterator_hasNext(), g_iterator_next(), GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, and GContainer::type.
void g_container_copy (GContainer * dest, const GContainer * src)
Copy the contents of one GContainer(p.) into another (not overwriting).
Copy the contents of one GContainer(p.) into another. Note that this function will not overwrite any other data in dest - instead, it will simply append the contents of src onto dest.
dest is the GContainer(p.) to copy data into
src is the GContainer(p.) to copy data from
Definition at line 394 of file gcontainer.c.
References ERROR, g_container_add(), g_container_get_iter(), g_iterator_hasNext(), and g_iterator_next().
Referenced by g_container_dup(), luau_copyProgInfo(), and luau_copyUpdate().
void g_container_destroy (GContainer * array)
Free a GContainer(p.) and all the pointers it stores.
Free both a GContainer(p.) and all the data stored within it. Convenient to use on the GPtrArray returned from luau_getAllPrograms.
array is the array to destroy
Definition at line 416 of file gcontainer.c.
References ERROR, g_container_free(), g_container_get_iter(), g_iterator_hasNext(), and g_iterator_next().
Referenced by freeMultAttribute(), g_container_destroy_type(), luau_versioncmp(), and parsePackage().
void g_container_destroy_type (GContType type, void * array)
Free an array of specified type and all the pointers it stores.
Definition at line 435 of file gcontainer.c.
References ERROR, g_container_destroy(), and g_container_new_from_data().
GContainer* g_container_dup (const GContainer * container)
Performs a shallow copy and returns a new GContainer(p.) object.
Definition at line 80 of file gcontainer.c.
References g_container_copy(), g_container_new(), and GContainer::type.
Referenced by copySetAttributes().
void* g_container_free (GContainer * container, gboolean freeAssoc)
Free the memory allocated to a GContainer(p.).
Definition at line 321 of file gcontainer.c.
References GContainer::data, ERROR, GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, and GContainer::type.
Referenced by freeSetAttributes(), g_container_convert(), g_container_destroy(), luau_checkForUpdates(), luau_checkKeyword(), luau_copyProgInfo(), luau_copyUpdate(), luau_getUpdateInfo(), luau_keywordsString(), parseMirrorIDs(), parsePackageAttrMirrors(), and parsePkgGroup().
gboolean g_container_get_iter (GIterator * iter, const GContainer * container)
Definition at line 221 of file gcontainer.c.
References GContainer::data, GIterator::data, ERROR, GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, GIterator::index, GContainer::type, and GIterator::type.
Referenced by addToMirrorList(), freeSetAttributes(), g_container_concat(), g_container_convert(), g_container_copy(), g_container_destroy(), getAttributeList(), luau_getUpdateInfo(), lutil_findString(), lutil_strjoin(), parseMirrorIDs(), parsePackageAttrMirrors(), and parsePkgGroup().
gboolean g_container_get_iter_last (GIterator * iter, const GContainer * container)
Definition at line 241 of file gcontainer.c.
References GContainer::data, GIterator::data, ERROR, GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, GIterator::index, GContainer::len, GContainer::type, and GIterator::type.
Referenced by getAttributeString().
gpointer g_container_index (const GContainer * container, guint index)
Definition at line 202 of file gcontainer.c.
References GContainer::data, ERROR, GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, GContainer::len, and GContainer::type.
Referenced by luau_versioncmp(), and lutil_strjoin().
GContainer* g_container_new (GContType type)
Definition at line 34 of file gcontainer.c.
References GContainer::data, ERROR, GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, GContainer::len, and GContainer::type.
Referenced by addToMirrorList(), g_container_convert(), g_container_dup(), getAttributeList(), initializeSetAttributes(), luau_parseXML_updates(), lutil_gsplit(), parseMirrorIDs(), parsePackageProperties(), and parsePkgGroup().
GContainer* g_container_new_from_data (GContType type, void * data)
Definition at line 55 of file gcontainer.c.
References GContainer::data, ERROR, GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, GContainer::len, and GContainer::type.
Referenced by g_container_destroy_type(), luau_checkKeyword(), luau_copyProgInfo(), luau_copyUpdate(), and luau_keywordsString().
gboolean g_container_remove (GContainer * container, const gpointer data)
Definition at line 118 of file gcontainer.c.
References GContainer::data, ERROR, GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, GContainer::len, and GContainer::type.
Referenced by g_container_remove_fast().
gboolean g_container_remove_fast (GContainer * container, const gpointer data)
Definition at line 147 of file gcontainer.c.
References GContainer::data, g_container_remove(), GCONT_PTR_ARRAY, GContainer::len, and GContainer::type.
gpointer g_container_remove_index (GContainer * container, guint index)
Definition at line 161 of file gcontainer.c.
References GContainer::data, ERROR, GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, GContainer::len, and GContainer::type.
Referenced by g_container_remove_index_fast().
gpointer g_container_remove_index_fast (GContainer * container, guint index)
Definition at line 188 of file gcontainer.c.
References GContainer::data, ERROR, g_container_remove_index(), GCONT_PTR_ARRAY, GContainer::len, and GContainer::type.
gpointer g_iterator_get (const GIterator * iter)
Definition at line 262 of file gcontainer.c.
References GIterator::data, ERROR, GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, GIterator::index, and GIterator::type.
Referenced by g_iterator_next(), and g_iterator_prev().
gboolean g_iterator_hasNext (const GIterator * iter)
Definition at line 292 of file gcontainer.c.
References GIterator::data, ERROR, GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, GIterator::index, and GIterator::type.
Referenced by addToMirrorList(), freeSetAttributes(), g_container_concat(), g_container_convert(), g_container_copy(), g_container_destroy(), getAttributeList(), luau_getUpdateInfo(), lutil_findString(), lutil_strjoin(), parseMirrorIDs(), parsePackageAttrMirrors(), and parsePkgGroup().
gboolean g_iterator_hasPrev (const GIterator * iter)
Definition at line 306 of file gcontainer.c.
References GIterator::data, ERROR, GCONT_LIST, GCONT_PTR_ARRAY, GCONT_SLIST, GIterator::index, and GIterator::type.
Referenced by getAttributeString().
gpointer g_iterator_next (GIterator * iter)
Definition at line 276 of file gcontainer.c.
References g_iterator_get(), and iterNext().
Referenced by addToMirrorList(), freeSetAttributes(), g_container_concat(), g_container_convert(), g_container_copy(), g_container_destroy(), getAttributeList(), luau_getUpdateInfo(), lutil_findString(), lutil_strjoin(), parseMirrorIDs(), parsePackageAttrMirrors(), and parsePkgGroup().
gpointer g_iterator_prev (GIterator * iter)
Definition at line 285 of file gcontainer.c.
References g_iterator_get(), and iterPrev().
Referenced by getAttributeString().