install.h File Reference
Package nstallation methods.
#include <glib.h>
Functions
gboolean luau_install_rpm (const char *filename, GError **err)
gboolean luau_install_deb (const char *filename, GError **err)
gboolean luau_install_src (const char *filename, GError **err)
gboolean luau_install_exec (const char *filename, GError **err)
gboolean luau_install_autopkg (const char *filename, GError **err)
Detailed Description
Package nstallation methods.
Allows Luau to automatically install supported package files (RPMs, DEBs, self-executing files, and autopackage files). May be preferable to override these functions and provide your own installation routines.
Definition in file install.h.
Function Documentation
gboolean luau_install_autopkg (const char * filename, GError ** err)
Definition at line 128 of file install.c.
References luau_install_exec().
Referenced by luau_installPackage().
gboolean luau_install_deb (const char * filename, GError ** err)
Definition at line 70 of file install.c.
References LUAU_INSTALL_ERROR, LUAU_INSTALL_ERROR_FAILED, and lutil_mprintf().
Referenced by luau_installPackage().
gboolean luau_install_exec (const char * filename, GError ** err)
Definition at line 104 of file install.c.
References LUAU_INSTALL_ERROR, LUAU_INSTALL_ERROR_FAILED, and LUAU_INSTALL_ERROR_INVALID_ARG.
Referenced by luau_install_autopkg(), and luau_installPackage().
gboolean luau_install_rpm (const char * filename, GError ** err)
Definition at line 41 of file install.c.
References LUAU_INSTALL_ERROR, LUAU_INSTALL_ERROR_FAILED, and lutil_mprintf().
Referenced by luau_installPackage().
gboolean luau_install_src (const char * filename, GError ** err)
Definition at line 99 of file install.c.
References LUAU_INSTALL_ERROR, and LUAU_INSTALL_ERROR_INVALID_ARG.
Referenced by luau_installPackage().