install.c File Reference
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include `util.h`
#include `error.h`
#include `libuau.h`
#include `install.h`
Functions
gboolean luau_install_rpm (const char *filename, GError **err)
gboolean luau_install_deb (const char *filename, GError **err)
gboolean luau_install_src (const char *filename, GError **err)
gboolean luau_install_exec (const char *filename, GError **err)
gboolean luau_install_autopkg (const char *filename, GError **err)
Function Documentation
gboolean luau_install_autopkg (const char * filename, GError ** err)
Definition at line 128 of file install.c.
References luau_install_exec().
Referenced by luau_installPackage().
gboolean luau_install_deb (const char * filename, GError ** err)
Definition at line 70 of file install.c.
References LUAU_INSTALL_ERROR, LUAU_INSTALL_ERROR_FAILED, and lutil_mprintf().
Referenced by luau_installPackage().
gboolean luau_install_exec (const char * filename, GError ** err)
Definition at line 104 of file install.c.
References LUAU_INSTALL_ERROR, LUAU_INSTALL_ERROR_FAILED, and LUAU_INSTALL_ERROR_INVALID_ARG.
Referenced by luau_install_autopkg(), and luau_installPackage().
gboolean luau_install_rpm (const char * filename, GError ** err)
Definition at line 41 of file install.c.
References LUAU_INSTALL_ERROR, LUAU_INSTALL_ERROR_FAILED, and lutil_mprintf().
Referenced by luau_installPackage().
gboolean luau_install_src (const char * filename, GError ** err)
Definition at line 99 of file install.c.
References LUAU_INSTALL_ERROR, and LUAU_INSTALL_ERROR_INVALID_ARG.
Referenced by luau_installPackage().