libuau.h File Reference
Interface to the libuau library.
#include <stdlib.h>
#include <glib.h>
Data Structures
struct ADate
Date structure.
struct APackage
Describe a specific package (ie, an RPM for an update).
struct AInterface
Describe the interface of a program. Only really relevant for libraries.
struct AUpdate
Describe all aspects of any type of update (software, message, etc.).
struct AQuantifier
struct AProgInfo
Describe an installed (and registered) program.
Defines
#define LUAU_VERSION_MAJOR 0
#define LUAU_VERSION_MINOR 1
#define LUAU_VERSION_PATCH 9
#define LUAU_XML_INTERFACE_MAJOR 1
#define LUAU_XML_INTERFACE_MINOR 2
#define LUAU_EMPTY 0
#define LUAU_RPM 1 << 0
#define LUAU_DEB 1 << 1
#define LUAU_SRC 1 << 2
#define LUAU_EXEC 1 << 3
#define LUAU_AUTOPKG 1 << 4
#define LUAU_UNKNOWN 1 << 7
#define LUAU_BASE_ERROR g_quark_from_static_string(`LUAU_BASE_ERROR`)
#define LUAU_UTIL_ERROR g_quark_from_static_string(`LUAU_UTIL_ERROR`)
#define LUAU_NET_ERROR g_quark_from_static_string(`LUAU_NET_ERROR`)
#define LUAU_INSTALL_ERROR g_quark_from_static_string(`LUAU_INSTALL_ERROR`)
#define LUAU_DB_ERROR g_quark_from_static_string(`LUAU_DB_ERROR`)
Typedefs
typedef guint32 APkgType
Describes a type of package (see LUAU_*type*, #define'd above).
typedef int(* APromptFunc)(const char *title, const char *msg, int nTotal, int nDefault, const char *choice1, va_list args)
typedef void(* ACallback)(void *data)
typedef void(* AFloatCallback)(float data)
typedef void(* ACallbackWithData)(void *callback_data, void *user_data)
typedef int(* AProgressCallback)(void *clientp, double dltotal, double dlnow, double ultotal, double ulnow)
Enumerations
enum AUpdateType { LUAU_SOFTWARE,
LUAU_MESSAGE,
LUAU_LIBUPDATE
 }
Describes an update type (software, message, luau config update).
enum AQuantType { LUAU_QUANT_FROM,
LUAU_QUANT_TO,
LUAU_QUANT_FOR
 }
enum AQuantDataType {
LUAU_QUANT_DATA_DATE,
LUAU_QUANT_DATA_VERSION,
LUAU_QUANT_DATA_INTERFACE,
LUAU_QUANT_DATA_KEYWORD,
LUAU_QUANT_DATA_INVALID
 }
enum LuauBaseError { LUAU_BASE_ERROR_PERMS,
LUAU_BASE_ERROR_ABORTED,
LUAU_BASE_ERROR_FAILED,
LUAU_BASE_ERROR_INVALID_ARG
 }
enum LuauNetError { LUAU_NET_ERROR_ABORTED,
LUAU_NET_ERROR_FAILED,
LUAU_NET_ERROR_INVALID_ARG
 }
enum LuauInstallError { LUAU_INSTALL_ERROR_ABORTED,
LUAU_INSTALL_ERROR_FAILED,
LUAU_INSTALL_ERROR_INVALID_ARG
 }
enum LuauUtilError { LUAU_UTIL_ERROR_ABORTED,
LUAU_UTIL_ERROR_FAILED,
LUAU_UTIL_ERROR_INVALID_ARG
 }
enum LuauDbError { LUAU_DB_ERROR_ABORTED,
LUAU_DB_ERROR_FAILED,
LUAU_DB_ERROR_INVALID_ARG
 }
Functions
gboolean luau_getProgInfoFromXML_url (AProgInfo *progInfo, const char *url, GError **err)
Read in program information from an XML file at specified URL.
gboolean luau_getProgInfoFromXML_data (AProgInfo *progInfo, const char *data, GError **err)
Read in program information from an XML file in memory.
gboolean luau_getUpdateInfo (AUpdate *update, const char *updateID, const AProgInfo *progInfo, GError **err)
Retrieve update info (type, description, etc.) corresponding to the given ID (and program).
GList * luau_checkForUpdates (const AProgInfo *info, GError **err)
Retrieve any new updates for the specified program.
GList * luau_checkForUpdates_url (const char *url, GError **err)
Retrieve all updates from the specified URL.
gboolean luau_installUpdate (const AProgInfo *info, const AUpdate *newUpdate, const APkgType type, GError **err)
Download and install an update of type type.
char * luau_downloadUpdate (const AProgInfo *info, const AUpdate *newUpdate, const APkgType type, const char *filename, GError **err)
Download but do not install an update of type type to filename.
gboolean luau_installPackage (const char *filename, const APkgType type, GError **err)
Install an already downloaded package.
void luau_registerPromptFunc (APromptFunc promptFunc)
Set a new function for prompting the user for input with.
void luau_registerProgressCallback (AProgressCallback callback)
Set a new function to callback (in order to show download progress) when downloading.
void luau_resetPromptFunc (void)
Reset the prompting function to the default function.
void luau_resetProgressCallback (void)
Reset the download callback function to the default function.
char * luau_dateString (const ADate *date)
Convert an ADate(p.) struct into a string.
char * luau_multPackageTypeString (APkgType types)
Convert an APkgType (of many types) into a string.
const char * luau_packageTypeString (APkgType type)
Convert an APkgType (of one type) into a (constant) string.
char * luau_progInfoString (const AProgInfo *info)
Convert an AProgInfo(p.) ptr into a string.
char * luau_keywordsString (const GPtrArray *keywords)
Convert an array of keywords into a string.
char * luau_interfaceString (const AInterface *interface)
Convert an AInterface(p.) into a string.
const char * luau_updateTypeString (AUpdateType type)
Convert an AUpdateType into a string.
gboolean luau_parseDate (ADate *date, const char *string)
Convert a date string (`MM/DD/YYYY`) into an ADate(p.) struct.
APkgType luau_parsePkgType (const char *typeString)
Convert a package type string into an APkgType.
gboolean luau_parseInterface (AInterface *interface, const char *intStr)
Convert an interface string (`x.y`) into an AInterface(p.).
GSList * luau_packageTypeList (APkgType types)
Convert an APkgType into a list of APkgType's.
APackage * luau_getUpdatePackage (const AUpdate *update, APkgType pkgType, GError **err)
Find the package of type pkgType in update.
gboolean luau_isOfType (APkgType query, APkgType type)
Check if package type type is included in package aggregate query.
char * luau_getPackageURL (APackage *pkgInfo, GError **err)
int luau_datecmp (ADate *d1, ADate *d2)
Compare two dates (works like strcmp but for ADate's).
int luau_versioncmp (const char *required, const char *current)
Compare two versions (works like strcmp but for version strings).
void luau_setKeyword (GPtrArray *keywords, const char *newKeyword)
Sets a keyword.
gboolean luau_unsetKeyword (GPtrArray *keywords, const char *oldKeyword)
Unsets a keyword.
gboolean luau_checkKeyword (const GPtrArray *keywords, const char *needle)
Checks to see if a keyword is set.
gboolean luau_isIncompatible (AUpdate *update)
See if an update has been marked as `Incompatible`.
gboolean luau_isHidden (AUpdate *update)
See if an update has been marked as `Hidden`.
gboolean luau_isOld (AUpdate *update)
See if an update has been marked as `Old`.
gboolean luau_isVisible (AUpdate *update)
See if an updates is visible (has not been marked as old, hidden, or incompatible).
gboolean luau_satisfiesInterface (const AInterface *wanted, const AInterface *needed)
Check if a given interface matches an interface that is needed.
gboolean luau_satisfiesQuant (const AQuantifier *needed, const AProgInfo *installed)
AQuantDataType luau_parseQuantDataType (const char *str)
void luau_copyUpdate (AUpdate *dest, const AUpdate *src)
Copy an AUpdate(p.) struct.
void luau_copyPackage (APackage *dest, const APackage *src)
Copy an APackage(p.) struct.
void luau_copyProgInfo (AProgInfo *dest, const AProgInfo *src)
Copy an AProgInfo(p.) struct.
void luau_copyInterface (AInterface *dest, const AInterface *src)
Copy an AInterfacestruct.
void luau_copyDate (ADate *dest, const ADate *src)
Copy an ADate(p.) struct.
void luau_copyQuants (GPtrArray *dest, const GPtrArray *src)
Copy an array of AQuantifiers.
void luau_copyQuant (AQuantifier *dest, const AQuantifier *src)
Copy an AQuantifier(p.) struct.
void luau_freeUpdateList (GList *updates)
Free an array of AUpdate's.
void luau_freeProgInfo (AProgInfo *ptr)
Free an AProgInfo(p.) struct pointer.
void luau_freeUpdateInfo (AUpdate *ptr)
Free an AUpdate(p.) struct pointer.
void luau_freePkgInfo (APackage *ptr)
Free an APackage(p.) struct pointer.
Detailed Description
Interface to the libuau library.
This is the one and only header file you'll need to use and understand in order to interface with libuau from a third party program. It provides all the necessary functionality for using libuau and is the only installed header file.
Definition in file libuau.h.
Define Documentation
#define LUAU_AUTOPKG 1 << 4
Definition at line 48 of file libuau.h.
Referenced by luau_installPackage(), luau_multPackageTypeString(), luau_packageTypeList(), luau_packageTypeString(), and luau_parsePkgType().
#define LUAU_BASE_ERROR g_quark_from_static_string(`LUAU_BASE_ERROR`)
Definition at line 51 of file libuau.h.
Referenced by luau_downloadUpdate(), luau_getPackageURL(), luau_getUpdateInfo(), luau_getUpdatePackage(), luau_installPackage(), luau_parseXML_progInfo(), luau_parseXML_updates(), and parseProgInfo().
#define LUAU_DB_ERROR g_quark_from_static_string(`LUAU_DB_ERROR`)
Definition at line 55 of file libuau.h.
#define LUAU_DEB 1 << 1
Definition at line 45 of file libuau.h.
Referenced by luau_installPackage(), luau_multPackageTypeString(), luau_packageTypeList(), luau_packageTypeString(), and luau_parsePkgType().
#define LUAU_EMPTY 0
Definition at line 43 of file libuau.h.
Referenced by luau_getUpdatePackage(), luau_multPackageTypeString(), and luau_packageTypeString().
#define LUAU_EXEC 1 << 3
Definition at line 47 of file libuau.h.
Referenced by luau_installPackage(), luau_multPackageTypeString(), luau_packageTypeList(), luau_packageTypeString(), and luau_parsePkgType().
#define LUAU_INSTALL_ERROR g_quark_from_static_string(`LUAU_INSTALL_ERROR`)
Definition at line 54 of file libuau.h.
Referenced by luau_install_deb(), luau_install_exec(), luau_install_rpm(), and luau_install_src().
#define LUAU_NET_ERROR g_quark_from_static_string(`LUAU_NET_ERROR`)
Definition at line 53 of file libuau.h.
Referenced by luau_net_downloadUpdate(), and luau_net_queryServer().
#define LUAU_RPM 1 << 0
Definition at line 44 of file libuau.h.
Referenced by luau_installPackage(), luau_multPackageTypeString(), luau_packageTypeList(), luau_packageTypeString(), and luau_parsePkgType().
#define LUAU_SRC 1 << 2
Definition at line 46 of file libuau.h.
Referenced by luau_installPackage(), luau_multPackageTypeString(), luau_packageTypeList(), luau_packageTypeString(), and luau_parsePkgType().
#define LUAU_UNKNOWN 1 << 7
Definition at line 49 of file libuau.h.
Referenced by luau_parsePkgType(), and parsePackageProperties().
#define LUAU_UTIL_ERROR g_quark_from_static_string(`LUAU_UTIL_ERROR`)
Definition at line 52 of file libuau.h.
#define LUAU_VERSION_MAJOR 0
Definition at line 36 of file libuau.h.
#define LUAU_VERSION_MINOR 1
Definition at line 37 of file libuau.h.
#define LUAU_VERSION_PATCH 9
Definition at line 38 of file libuau.h.
#define LUAU_XML_INTERFACE_MAJOR 1
Definition at line 40 of file libuau.h.
Referenced by luau_parseXML_progInfo(), and luau_parseXML_updates().
#define LUAU_XML_INTERFACE_MINOR 2
Definition at line 41 of file libuau.h.
Referenced by luau_parseXML_progInfo(), and luau_parseXML_updates().
Typedef Documentation
typedef void(* ACallback)(void *data)
Definition at line 107 of file libuau.h.
typedef void(* ACallbackWithData)(void *callback_data, void *user_data)
Definition at line 109 of file libuau.h.
typedef void(* AFloatCallback)(float data)
Definition at line 108 of file libuau.h.
typedef guint32 APkgType
Describes a type of package (see LUAU_*type*, #define'd above).
Definition at line 65 of file libuau.h.
Referenced by luau_parsePkgType().
typedef int(* AProgressCallback)(void *clientp, double dltotal, double dlnow, double ultotal, double ulnow)
Definition at line 110 of file libuau.h.
Referenced by luau_registerProgressCallback().
typedef int(* APromptFunc)(const char *title, const char *msg, int nTotal, int nDefault, const char *choice1, va_list args)
Definition at line 105 of file libuau.h.
Referenced by luau_registerPromptFunc().
Enumeration Type Documentation
enum AQuantDataType
Enumeration values:
LUAU_QUANT_DATA_DATE
LUAU_QUANT_DATA_VERSION
LUAU_QUANT_DATA_INTERFACE
LUAU_QUANT_DATA_KEYWORD
LUAU_QUANT_DATA_INVALID
Definition at line 76 of file libuau.h.
Referenced by luau_parseQuantDataType(), and parseGenericInfo().
enum AQuantType
Enumeration values:
LUAU_QUANT_FROM
LUAU_QUANT_TO
LUAU_QUANT_FOR
Definition at line 72 of file libuau.h.
enum AUpdateType
Describes an update type (software, message, luau config update).
Enumeration values:
LUAU_SOFTWARE
LUAU_MESSAGE
LUAU_LIBUPDATE
Definition at line 68 of file libuau.h.
enum LuauBaseError
Enumeration values:
LUAU_BASE_ERROR_PERMS
LUAU_BASE_ERROR_ABORTED
LUAU_BASE_ERROR_FAILED
LUAU_BASE_ERROR_INVALID_ARG
Definition at line 83 of file libuau.h.
enum LuauDbError
Enumeration values:
LUAU_DB_ERROR_ABORTED
LUAU_DB_ERROR_FAILED
LUAU_DB_ERROR_INVALID_ARG
Definition at line 100 of file libuau.h.
enum LuauInstallError
Enumeration values:
LUAU_INSTALL_ERROR_ABORTED
LUAU_INSTALL_ERROR_FAILED
LUAU_INSTALL_ERROR_INVALID_ARG
Definition at line 92 of file libuau.h.
enum LuauNetError
Enumeration values:
LUAU_NET_ERROR_ABORTED
LUAU_NET_ERROR_FAILED
LUAU_NET_ERROR_INVALID_ARG
Definition at line 88 of file libuau.h.
enum LuauUtilError
Enumeration values:
LUAU_UTIL_ERROR_ABORTED
LUAU_UTIL_ERROR_FAILED
LUAU_UTIL_ERROR_INVALID_ARG
Definition at line 96 of file libuau.h.
Function Documentation
GList* luau_checkForUpdates (const AProgInfo * info, GError ** err)
Retrieve any new updates for the specified program.
Check for updates for the given ID by contacting the server for the program and downloading and parsing the updates file. Returned GPtrArray must be free'd (use luau_freeUpdateArray).
info describes the program we want to check updates for.
Returns: an array of updates for the program in question (must be free'd).
See also: luau_freeUpdateArray
Definition at line 161 of file libuau.c.
References categorizeUpdates(), DBUGOUT, g_container_free(), AProgInfo::id, luau_net_queryServer(), and AProgInfo::url.
Referenced by luau_checkForUpdates_url().
GList* luau_checkForUpdates_url (const char * url, GError ** err)
Retrieve all updates from the specified URL.
Definition at line 182 of file libuau.c.
References AProgInfo::id, luau_checkForUpdates(), and AProgInfo::url.
gboolean luau_checkKeyword (const GPtrArray * keywords, const char * needle)
Checks to see if a keyword is set.
See if a keyword exists in a keyword array.
keywords is the array to check
needle is the keyword to look for
Returns: if it exists in the array
Definition at line 1003 of file libuau.c.
References g_container_free(), g_container_new_from_data(), GCONT_PTR_ARRAY, and lutil_findString().
Referenced by luau_isHidden(), luau_isIncompatible(), luau_isOld(), and luau_satisfiesQuant().
void luau_copyDate (ADate * dest, const ADate * src)
Copy an ADate(p.) struct.
Copy an ADate(p.) src to dest. If src or dest is NULL, the operation will be aborted.
dest is the ADate(p.) struct to copy into.
src is the ADate(p.) struct to copy from.
Definition at line 1359 of file libuau.c.
References ADate::day, DBUGOUT, ADate::month, and ADate::year.
Referenced by luau_copyProgInfo(), luau_copyQuant(), and luau_copyUpdate().
void luau_copyInterface (AInterface * dest, const AInterface * src)
Copy an AInterfacestruct.
Copy an AInterface(p.) src to dest. If src or dest is NULL, the operation will be aborted.
dest is the AInterface(p.) struct to copy into.
src is the AInterface(p.) struct to copy from.
Definition at line 1343 of file libuau.c.
References DBUGOUT, AInterface::major, and AInterface::minor.
Referenced by luau_copyProgInfo(), and luau_copyUpdate().
void luau_copyPackage (APackage * dest, const APackage * src)
Copy an APackage(p.) struct.
Definition at line 1268 of file libuau.c.
References DBUGOUT, APackage::md5sum, APackage::mirrors, APackage::size, and APackage::type.
Referenced by luau_copyUpdate().
void luau_copyProgInfo (AProgInfo * dest, const AProgInfo * src)
Copy an AProgInfo(p.) struct.
Copy an AProgInfo(p.) src to dest. If src or dest is NULL, the operation will be aborted.
dest is the AProgInfo(p.) struct to copy into.
src is the AProgInfo(p.) struct to copy from.
Definition at line 1303 of file libuau.c.
References AProgInfo::date, DBUGOUT, AProgInfo::desc, AProgInfo::fullname, g_container_copy(), g_container_free(), g_container_new_from_data(), GCONT_PTR_ARRAY, AProgInfo::id, AProgInfo::interface, AProgInfo::keywords, luau_copyDate(), luau_copyInterface(), AProgInfo::shortname, AProgInfo::url, and AProgInfo::version.
void luau_copyQuant (AQuantifier * dest, const AQuantifier * src)
Copy an AQuantifier(p.) struct.
Definition at line 1382 of file libuau.c.
References AQuantifier::data, AQuantifier::dtype, ERROR, luau_copyDate(), LUAU_QUANT_DATA_DATE, LUAU_QUANT_DATA_INTERFACE, LUAU_QUANT_DATA_KEYWORD, LUAU_QUANT_DATA_VERSION, and AQuantifier::qtype.
Referenced by luau_copyQuants().
void luau_copyQuants (GPtrArray * dest, const GPtrArray * src)
Copy an array of AQuantifiers.
Definition at line 1370 of file libuau.c.
References luau_copyQuant().
Referenced by luau_copyUpdate().
void luau_copyUpdate (AUpdate * dest, const AUpdate * src)
Copy an AUpdate(p.) struct.
Copy an AUpdate(p.) src to dest. If src or dest is NULL, the operation will be aborted.
dest is the AUpdate(p.) struct to copy into.
src is the AUpdate(p.) struct to copy from.
Definition at line 1201 of file libuau.c.
References AUpdate::availableFormats, AUpdate::date, DBUGOUT, AUpdate::fullDesc, g_container_copy(), g_container_free(), g_container_new_from_data(), GCONT_PTR_ARRAY, AUpdate::id, AUpdate::interface, AUpdate::keywords, luau_copyDate(), luau_copyInterface(), luau_copyPackage(), luau_copyQuants(), AUpdate::newURL, AUpdate::newVersion, AUpdate::packages, AUpdate::quantifiers, AUpdate::shortDesc, and AUpdate::type.
Referenced by luau_getUpdateInfo().
int luau_datecmp (ADate * d1, ADate * d2)
Compare two dates (works like strcmp but for ADate's).
Compare two dates and return an integer accordingly (in style of strcmp).
d1 is the first date
d2 is the date to compare d1 with
Returns:
-1 if d1 is earlier than d2,
0 if d1 is the same as d2, or
+1 if d1 is later than d2.
Definition at line 599 of file libuau.c.
References ADate::day, lutil_intcmp(), ADate::month, and ADate::year.
Referenced by luau_satisfiesQuant().
char* luau_dateString (const ADate * date)
Convert an ADate(p.) struct into a string.
Convert an ADate(p.) into a string (`YYYY-MM-DD`). Returns `(null)` if date == NULL. Returned string must be free'd.
date is the date to convert into a string
Returns: a string representing the date - must be free'd.
Definition at line 488 of file libuau.c.
References ADate::day, lutil_mprintf(), ADate::month, and ADate::year.
Referenced by luau_progInfoString().
char* luau_downloadUpdate (const AProgInfo * info, const AUpdate * newUpdate, const APkgType type, const char * downloadTo, GError ** err)
Download but do not install an update of type type to filename.
Download an update to the specified location. Returned string must be examined and must be free'd. Do not assume that the update was downloaded exactly to downloadTo.
info describes the program we want to download an update for.
newUpdate describes the update we want to download.
type is which kind of update (eg. RPM, DEB, ...) we want to download
downloadTo specifies where we want to download this update to. If a directory is specified, it will be downloaded to that directory with the original filename.
Returns: where this update was actually downloaded (should be == downloadTo -unless- downloadTo is a directory) (must be free'd), or NULL if the operation was unsuccessful.
See also: luau_installPackage(p.)
Definition at line 246 of file libuau.c.
References DBUGOUT, LUAU_BASE_ERROR, LUAU_BASE_ERROR_ABORTED, LUAU_BASE_ERROR_INVALID_ARG, LUAU_BASE_ERROR_PERMS, luau_getPackageURL(), luau_getUpdatePackage(), luau_net_downloadUpdate(), lutil_error_prompt(), and lutil_vstrcreate().
Referenced by luau_installUpdate().
void luau_freePkgInfo (APackage * ptr)
Free an APackage(p.) struct pointer.
Free an APackage(p.) struct.
ptr is the struct to free.
Definition at line 1503 of file libuau.c.
References APackage::mirrors.
Referenced by luau_freeUpdateInfo().
void luau_freeProgInfo (AProgInfo * ptr)
Free an AProgInfo(p.) struct pointer.
Free an AProgInfo(p.) struct.
ptr is the struct to free
Definition at line 1431 of file libuau.c.
References AProgInfo::date, AProgInfo::desc, AProgInfo::displayVersion, AProgInfo::fullname, AProgInfo::id, AProgInfo::keywords, nnull_g_free, AProgInfo::shortname, AProgInfo::url, and AProgInfo::version.
void luau_freeUpdateInfo (AUpdate * ptr)
Free an AUpdate(p.) struct pointer.
Free an AUpdate(p.) struct
ptr is the struct to free
Definition at line 1458 of file libuau.c.
References AQuantifier::data, AUpdate::date, AUpdate::fullDesc, AUpdate::id, AUpdate::keywords, luau_freePkgInfo(), AUpdate::newURL, AUpdate::newVersion, nnull_g_free, AUpdate::packages, AUpdate::quantifiers, and AUpdate::shortDesc.
Referenced by luau_freeUpdateList().
void luau_freeUpdateList (GList * updates)
Free an array of AUpdate's.
Free an update list, as returned by luau_checkForUpdates(p.)
updates is the updates array to free
Definition at line 1412 of file libuau.c.
References luau_freeUpdateInfo().
Referenced by luau_getUpdateInfo().
char* luau_getPackageURL (APackage * pkgInfo, GError ** err)
Definition at line 834 of file libuau.c.
References DBUGOUT, LUAU_BASE_ERROR, LUAU_BASE_ERROR_INVALID_ARG, and APackage::mirrors.
Referenced by luau_downloadUpdate(), and luau_net_downloadUpdate().
gboolean luau_getProgInfoFromXML_data (AProgInfo * progInfo, const char * data, GError ** err)
Read in program information from an XML file in memory.
Definition at line 82 of file libuau.c.
References luau_parseXML_progInfo().
gboolean luau_getProgInfoFromXML_url (AProgInfo * progInfo, const char * url, GError ** err)
Read in program information from an XML file at specified URL.
Definition at line 60 of file libuau.c.
References luau_parseXML_progInfo(), and lutil_ftp_getURL().
gboolean luau_getUpdateInfo (AUpdate * updateInfo, const char * updateID, const AProgInfo * progInfo, GError ** err)
Retrieve update info (type, description, etc.) corresponding to the given ID (and program).
Retrieve information for update updateID for program described by progInfo. Contacts server for program in question to retrieve all updates and then extracts the one matching updateID. Use luau_freeUpdateInfo(p.) to free the data associated with updateInfo
updateInfo is an AUpdate(p.) struct pointer where the data will be stored
updateID is the ID for the update wanted.
progInfo describes the program for which we're looking up an update.
Returns: whether the operation was successful
See also: luau_freeUpdateInfo(p.)
Definition at line 113 of file libuau.c.
References categorizeUpdate(), g_container_free(), g_container_get_iter(), g_iterator_hasNext(), g_iterator_next(), AProgInfo::id, AUpdate::id, LUAU_BASE_ERROR, LUAU_BASE_ERROR_INVALID_ARG, luau_copyUpdate(), luau_freeUpdateList(), luau_net_queryServer(), and lutil_streq().
APackage* luau_getUpdatePackage (const AUpdate * update, APkgType pkgType, GError ** err)
Find the package of type pkgType in update.
Find and return an APackage(p.) struct of the type pkgType from an AUpdate(p.). If one does not exist, return NULL.
update is the update to look in.
pkgType is the package type to find
Returns: the corresponding APackage(p.) struct ptr, or NULL otherwise.
Definition at line 446 of file libuau.c.
References LUAU_BASE_ERROR, LUAU_BASE_ERROR_INVALID_ARG, LUAU_EMPTY, luau_packageTypeString(), AUpdate::packages, and APackage::type.
Referenced by luau_downloadUpdate().
gboolean luau_installPackage (const char * filename, const APkgType type, GError ** err)
Install an already downloaded package.
Installs a package that has already been downloaded.
filename is the location where the update package can be found.
type is the type of update (eg. RPM, DEB, ...) we're installing.
Returns: whether the operation was successful.
Definition at line 327 of file libuau.c.
References LUAU_AUTOPKG, LUAU_BASE_ERROR, LUAU_BASE_ERROR_INVALID_ARG, LUAU_DEB, LUAU_EXEC, luau_install_autopkg(), luau_install_deb(), luau_install_exec(), luau_install_rpm(), luau_install_src(), LUAU_RPM, and LUAU_SRC.
Referenced by luau_installUpdate().
gboolean luau_installUpdate (const AProgInfo * info, const AUpdate * newUpdate, const APkgType type, GError ** err)
Download and install an update of type type.
Install an update.
info describes the program we're updating
newUpdate describes the update we're installing
type is the type of package (eg, RPM, DEB, ...) we want to install.
Returns: whether the operation succeeded
Definition at line 205 of file libuau.c.
References luau_downloadUpdate(), luau_installPackage(), and lutil_getTempFilename().
char* luau_interfaceString (const AInterface * interface)
Convert an AInterface(p.) into a string.
Take an AInterface(p.) struct and convert it into a string of form `x.y`, where x is the major and y the minor interface version. If the major and minor values are both -1, then NULL will be returned. The returned string is allocated dynamically and must be free'd.
interface is the AInterface(p.) struct to convert into a string
Returns: a newly allocated string representing the AInterface(p.) (must be free'd).
Definition at line 1180 of file libuau.c.
References lutil_mprintf(), AInterface::major, and AInterface::minor.
gboolean luau_isHidden (AUpdate * update)
See if an update has been marked as `Hidden`.
Check if an update has been marked as `hidden`
update is the update to check
Returns: whether it has been marked as hidden
Definition at line 1039 of file libuau.c.
References AUpdate::keywords, and luau_checkKeyword().
Referenced by luau_isVisible().
gboolean luau_isIncompatible (AUpdate * update)
See if an update has been marked as `Incompatible`.
Check if an update has been marked as `incompatible`
update is the update to check
Returns: whether it has been marked as incompatible
Definition at line 1025 of file libuau.c.
References AUpdate::keywords, and luau_checkKeyword().
Referenced by luau_isVisible().
gboolean luau_isOfType (APkgType query, APkgType type)
Check if package type type is included in package aggregate query.
Check to see if query contains type type.
query is the APkgType to check
type is the type to see if query contains.
Returns: TRUE if it does, FALSE otherwise
Definition at line 739 of file libuau.c.
Referenced by luau_multPackageTypeString(), and luau_packageTypeList().
gboolean luau_isOld (AUpdate * update)
See if an update has been marked as `Old`.
Definition at line 1047 of file libuau.c.
References AUpdate::keywords, and luau_checkKeyword().
Referenced by luau_isVisible().
gboolean luau_isVisible (AUpdate * update)
See if an updates is visible (has not been marked as old, hidden, or incompatible).
Definition at line 1055 of file libuau.c.
References luau_isHidden(), luau_isIncompatible(), and luau_isOld().
char* luau_keywordsString (const GPtrArray * keywords)
Convert an array of keywords into a string.
Convert an array of keywords into a string, separated by commas. Resultant string must be free'd.
keywords are the keywords to convert
Returns: a string representing them (must be free'd)
Definition at line 942 of file libuau.c.
References g_container_free(), g_container_new_from_data(), GCONT_PTR_ARRAY, and lutil_strjoin().
Referenced by luau_progInfoString().
char* luau_multPackageTypeString (APkgType types)
Convert an APkgType (of many types) into a string.
Convert an APkgType of multiple package types into a string. Resultant string must be free'd.
types is the APkgType representing multiple types to convert
Returns: a space-separated string of the types it contains
See also: luau_packageTypeString(p.)
Definition at line 753 of file libuau.c.
References ERROR, LUAU_AUTOPKG, LUAU_DEB, LUAU_EMPTY, LUAU_EXEC, luau_isOfType(), LUAU_RPM, LUAU_SRC, and lutil_createString().
GSList* luau_packageTypeList (APkgType types)
Convert an APkgType into a list of APkgType's.
Take an APkgType of multiple types and convert it into a list of single APkgType's.
types is an APkgType of multiple types
Returns: a GSList of single APkgType's
Definition at line 879 of file libuau.c.
References LUAU_AUTOPKG, LUAU_DEB, LUAU_EXEC, luau_isOfType(), LUAU_RPM, and LUAU_SRC.
const char* luau_packageTypeString (APkgType type)
Convert an APkgType (of one type) into a (constant) string.
Convert an APkgType of one package type into a string. Resultant string should not be free'd (constant string).
type is an APkgType of only one type
Returns: a constant string representing it
See also: luau_multPackageTypeString(p.)
Definition at line 791 of file libuau.c.
References LUAU_AUTOPKG, LUAU_DEB, LUAU_EMPTY, LUAU_EXEC, LUAU_RPM, and LUAU_SRC.
Referenced by luau_getUpdatePackage().
gboolean luau_parseDate (ADate * date, const char * string)
Convert a date string (`MM/DD/YYYY`) into an ADate(p.) struct.
Convert a string of format `YYYY-MM-DD` into an ADate(p.). If string == NULL or string is the empty string, all the fields of the resultant ADate(p.) will be set to 0.
date is the ADate(p.) to write the parsed information into
string is the string to convert to an ADate(p.)
Returns: whether the operation was successful
Definition at line 509 of file libuau.c.
References ADate::day, DBUGOUT, ERROR, ADate::month, and ADate::year.
Referenced by parseGenericInfo(), and parseQuantData().
gboolean luau_parseInterface (AInterface * interface, const char * intStr)
Convert an interface string (`x.y`) into an AInterface(p.).
Take a string (`x.y`, where x is the major and y the minor interface version)and convert it into an AInterface(p.), writing the data into interface. If intStr == NULL or there is an error in reading the string, then both major and minor will be set to -1.
interface is the AInterface(p.) struct to write data into
intStr is the string to parse (of form `x.y`)
Returns: whether the operation was successful
Definition at line 1152 of file libuau.c.
References lutil_isCompletelyBlank(), AInterface::major, and AInterface::minor.
Referenced by luau_parseXML_progInfo(), luau_parseXML_updates(), parseQuantData(), and parseSoftware().
APkgType luau_parsePkgType (const char * typeString)
Convert a package type string into an APkgType.
Take a string representing a package type (`RPM`, `DEB`, etc.) and convert it into an APkgType.
typeString is the string to convert
Returns: the corresponding APkgType, or LUAU_UNKNOWN if unrecognized
See also: luau_packageTypeList(p.)
Definition at line 822 of file libuau.c.
References APkgType, LUAU_AUTOPKG, LUAU_DEB, LUAU_EXEC, LUAU_RPM, LUAU_SRC, LUAU_UNKNOWN, and lutil_strcaseeq().
Referenced by parsePackageProperties().
AQuantDataType luau_parseQuantDataType (const char * str)
Definition at line 1124 of file libuau.c.
References AQuantDataType, LUAU_QUANT_DATA_DATE, LUAU_QUANT_DATA_INTERFACE, LUAU_QUANT_DATA_INVALID, LUAU_QUANT_DATA_KEYWORD, LUAU_QUANT_DATA_VERSION, and lutil_strcaseeq().
Referenced by parseGenericInfo().
char* luau_progInfoString (const AProgInfo * info)
Convert an AProgInfo(p.) ptr into a string.
Convert an AProgInfo(p.) struct into a string. Resultant string must be free'd.
info is a AProgInfo(p.) struct to convert
Returns: a new allocated string representing it (must be free'd).
Definition at line 920 of file libuau.c.
References AProgInfo::date, AProgInfo::desc, AProgInfo::fullname, AProgInfo::id, AProgInfo::keywords, luau_dateString(), luau_keywordsString(), lutil_mprintf(), AProgInfo::url, and AProgInfo::version.
void luau_registerProgressCallback (AProgressCallback callback)
Set a new function to callback (in order to show download progress) when downloading.
Set the function to display download progress with. See the definition of AProgressFunc for specific function parameters (and maybe the libcurl documentation too while you're at it - specifically the CURLOPT_PROGRESSFUNC option). Default behavior is not to display anything.
callback is the new progress callback to use.
See also: AProgressCallback(p.)
Definition at line 395 of file libuau.c.
References AProgressCallback, and lutil_ftp_setCallbackFunc().
void luau_registerPromptFunc (APromptFunc promptFunc)
Set a new function for prompting the user for input with.
Set the function to prompt the user for input with. See the definition of APromptFunc for specific function parameters. Note that the default behavior (if you don't define a new one) is simply not to prompt the user and select the default choice. This is probably not what you want!
promptFunc is the new prompting function to use
See also: APromptFunc(p.)
Definition at line 380 of file libuau.c.
References APromptFunc, and lutil_error_setPromptFunc().
void luau_resetProgressCallback (void)
Reset the download callback function to the default function.
Reset the progress callback (which doesn't display anything).
See also: luau_registerProgressCallback(p.)
Definition at line 427 of file libuau.c.
References lutil_ftp_resetCallbackFunc().
void luau_resetPromptFunc (void)
Reset the prompting function to the default function.
Reset the prompting facilities to their default behavior (that is, don't ask but just select the default option).
See also: luau_registerPromptFunc(p.)
Definition at line 417 of file libuau.c.
References lutil_error_resetPromptFunc().
gboolean luau_satisfiesInterface (const AInterface * wanted, const AInterface * needed)
Check if a given interface matches an interface that is needed.
Check if a given program/update interface satisfies the one needed. Conditions for being satisfactory:
wanted->major == needed->major
wanted->minor >= needed->minor
wanted is the AInterface(p.) we want to check
needed is the AInterface(p.) to test against (the `needed` interface)
Returns: whether wanted satisfies needed
Definition at line 1072 of file libuau.c.
References AInterface::major, and AInterface::minor.
Referenced by luau_parseXML_progInfo(), luau_parseXML_updates(), and luau_satisfiesQuant().
gboolean luau_satisfiesQuant (const AQuantifier * needed, const AProgInfo * installed)
Definition at line 1077 of file libuau.c.
References AQuantifier::data, AProgInfo::date, AQuantifier::dtype, ERROR, AProgInfo::interface, AProgInfo::keywords, luau_checkKeyword(), luau_datecmp(), LUAU_QUANT_DATA_DATE, LUAU_QUANT_DATA_INTERFACE, LUAU_QUANT_DATA_KEYWORD, LUAU_QUANT_DATA_VERSION, LUAU_QUANT_FOR, LUAU_QUANT_FROM, LUAU_QUANT_TO, luau_satisfiesInterface(), luau_versioncmp(), AQuantifier::qtype, and AProgInfo::version.
Referenced by isIncompatible().
void luau_setKeyword (GPtrArray * keywords, const char * newKeyword)
Sets a keyword.
Add a new keyword to a keyword array.
keywords is the keyword array to add on to
newKeyword is the new keyword to add
Definition at line 964 of file libuau.c.
gboolean luau_unsetKeyword (GPtrArray * keywords, const char * oldKeyword)
Unsets a keyword.
Remove a keyword from a keyword array. Return if it was there in the first place.
keywords is the keyword array to edit
oldKeyword is the keyword to remove
Returns: whether the keyword existed in the array at all
Definition at line 978 of file libuau.c.
References lutil_streq().
const char* luau_updateTypeString (AUpdateType type)
Convert an AUpdateType into a string.
Convert an AUpdateType into a constant string. Resultant string should not be free'd.
type is an AUpdateType to convert
Returns: a constant string representing it
Definition at line 904 of file libuau.c.
References LUAU_LIBUPDATE, LUAU_MESSAGE, and LUAU_SOFTWARE.
int luau_versioncmp (const char * required, const char * current)
Compare two versions (works like strcmp but for version strings).
Definition at line 651 of file libuau.c.
References compareAlphaNumeric(), g_container_destroy(), g_container_index(), GContainer::len, lutil_containsAlpha(), lutil_gsplit(), lutil_streq(), and lutil_strToLower().
Referenced by isOld(), and luau_satisfiesQuant().