luau-register.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <getopt.h>
#include <malloc.h>
#include <string.h>
#include <glib.h>
#include `libuau.h`
#include `database.h`
#include `util.h`
Functions
void printUsage (void)
option * getLongOptions ()
int main (int argc, char *argv[])
Function Documentation
struct option * getLongOptions () [static]
Definition at line 191 of file luau-register.c.
References getLongOptions().
Referenced by getLongOptions(), and main().
int main (int argc, char * argv[])
Definition at line 41 of file luau-register.c.
References AProgInfo::date, AProgInfo::desc, AProgInfo::fullname, getLongOptions(), AProgInfo::id, AProgInfo::interface, AProgInfo::keywords, luau_copyInterface(), luau_db_create(), luau_deleteApp(), luau_freeProgInfo(), luau_getProgInfo(), luau_parseDate(), luau_parseInterface(), luau_registerNewApp(), lutil_gsplit(), printUsage(), AProgInfo::shortname, AProgInfo::url, and AProgInfo::version.
void printUsage (void) [static]
Definition at line 169 of file luau-register.c.
References lutil_printIndented().
Referenced by main().