luau.c File Reference
Automatically update registered programs from the command line.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include <unistd.h>
#include <readline/readline.h>
#include <readline/history.h>
#include <glib.h>
#include `libuau.h`
#include `util.h`
#include `error.h`
#include `parse.h`
Functions
void MSG (int level, const char *template,...) __attribute__((format(printf
void printUsage (void)
option * getLongOptions (void)
gboolean downloadUpdate (const char *ID, const char *filename, const char *program, APkgType type)
gboolean installUpdate (const char *ID, const char *program, APkgType type)
int getUpdates (const char *program, APkgType type)
void runInteractive (void)
void printInteractiveHelp (void)
int list (const char *program)
gint compareUpdates (gconstpointer p1, gconstpointer p2, gpointer data)
int progressCallback (void *clientp, double dltotal, double dlnow, double ultotal, double ulnow)
int prompt (const char *title, const char *msg, int nTotal, int nDefault, const char *choice1, va_list args)
void send_email (const char *to, const char *from, const char *subject, const char *message)
int main (int argc, char *argv[])
Variables
int verbosity = 1
gboolean outputToString = FALSE
GString * outputString = NULL
Detailed Description
Automatically update registered programs from the command line.
Command line interface to use all the basic features of the luau library. Supports downloading, installing, and viewing updates, and listing and registering programs.
Definition in file luau.c.
Function Documentation
gint compareUpdates (gconstpointer p1, gconstpointer p2, gpointer data) [static]
Definition at line 727 of file luau.c.
References AUpdate::date, ERROR, AUpdate::id, luau_datecmp(), lutil_intcmp(), lutil_strcaseeq(), and AUpdate::type.
gboolean downloadUpdate (const char * ID, const char * filename, const char * program, APkgType type) [static]
Definition at line 225 of file luau.c.
References DBUGOUT, ERROR, AUpdate::fullDesc, luau_downloadUpdate(), luau_freeProgInfo(), luau_freeUpdateInfo(), luau_getProgInfo(), luau_getUpdateInfo(), LUAU_LIBUPDATE, LUAU_MESSAGE, LUAU_SOFTWARE, lutil_printIndented(), MSG, AUpdate::newURL, AUpdate::shortDesc, AUpdate::type, and verbosity.
Referenced by main(), and runInteractive().
struct option * getLongOptions (void) [static]
Definition at line 657 of file luau.c.
References getLongOptions().
Referenced by getLongOptions().
int getUpdates (const char * program, APkgType type) [static]
Definition at line 322 of file luau.c.
References AUpdate::availableFormats, curr, ERROR, AUpdate::id, luau_checkForUpdates(), luau_freeProgInfo(), luau_freeUpdateArray(), luau_getAllPrograms(), luau_getProgInfo(), luau_isHidden(), luau_isIncompatible(), luau_multPackageTypeString(), LUAU_SOFTWARE, luau_updateTypeString(), MSG, outputToString, AUpdate::shortDesc, AUpdate::type, updates, and verbosity.
Referenced by main(), and runInteractive().
gboolean installUpdate (const char * ID, const char * program, APkgType type) [static]
Definition at line 281 of file luau.c.
References ERROR, luau_freeProgInfo(), luau_freeUpdateInfo(), luau_getProgInfo(), luau_getUpdateInfo(), luau_installUpdate(), luau_registerNewApp(), LUAU_SOFTWARE, MSG, AUpdate::newURL, AUpdate::type, and AProgInfo::url.
Referenced by main(), and runInteractive().
int list (const char * program) [static]
Definition at line 567 of file luau.c.
References AProgInfo::desc, FATAL_ERROR, luau_freeProgInfo(), luau_getAllPrograms(), luau_getProgInfo(), lutil_destroyArray(), lutil_streq(), lutil_vstrcreate(), MSG, AProgInfo::shortname, AProgInfo::url, verbosity, and AProgInfo::version.
Referenced by main(), MSG(), and runInteractive().
int main (int argc, char * argv[])
Definition at line 72 of file luau.c.
References APkgType, downloadUpdate(), ERROR, file, getLongOptions(), getUpdates(), installUpdate(), list(), LUAU_EMPTY, luau_parsePkgType(), luau_registerProgressCallback(), luau_registerPromptFunc(), LUAU_UNKNOWN, MSG, outputString, outputToString, printUsage(), progressCallback(), prompt(), runInteractive(), send_email(), and verbosity.
void MSG (int level, const char * template, ...) [static]
Definition at line 834 of file luau.c.
References list(), lutil_valistToString(), outputString, outputToString, and verbosity.
void printInteractiveHelp (void) [static]
Definition at line 546 of file luau.c.
References MSG.
Referenced by runInteractive().
void printUsage (void) [static]
Definition at line 630 of file luau.c.
References MSG.
int progressCallback (void * clientp, double dltotal, double dlnow, double ultotal, double ulnow) [static]
Definition at line 745 of file luau.c.
Referenced by main().
int prompt (const char * title, const char * msg, int nTotal, int nDefault, const char * choice1, va_list args) [static]
Definition at line 771 of file luau.c.
References MSG, and prompt().
Referenced by main(), and prompt().
void runInteractive (void) [static]
Definition at line 432 of file luau.c.
References APkgType, LUAU_parsedLine::args, downloadUpdate(), ERROR, getUpdates(), installUpdate(), LUAU_parsedLine::keyword, list(), LUAU_EMPTY, luau_parsePkgType(), LUAU_VERSION_MAJOR, LUAU_VERSION_MINOR, LUAU_VERSION_PATCH, lutil_parse_freeParsedLine(), lutil_parse_parseLine(), lutil_parse_parseSymbol(), MSG, and printInteractiveHelp().
Referenced by main().
void send_email (const char * to, const char * from, const char * subject, const char * message) [static]
Definition at line 803 of file luau.c.
References len, and lutil_createString().
Referenced by main().
Variable Documentation
GString* outputString = NULL [static]
Definition at line 52 of file luau.c.
Referenced by main(), and MSG().
gboolean outputToString = FALSE [static]
Definition at line 51 of file luau.c.
Referenced by getUpdates(), main(), and MSG().
int verbosity = 1 [static]
Definition at line 50 of file luau.c.
Referenced by downloadUpdate(), getUpdates(), list(), main(), and MSG().