md5.h File Reference
Compute md5 sums.
#include <sys/types.h>
#include <glib.h>
#include `util.h`
Data Structures
struct MD5Context
Defines
#define MD5_HASHBYTES 16
Typedefs
typedef MD5Context MD5_CTX
Functions
char * lutil_md5_file (const char *filename, char *buf, GError **err)
Compute an md5sum of the given file.
char * lutil_md5_data (const unsigned char *data, unsigned int len, char *buf, GError **err)
Compute an md5sum of the given data.
Detailed Description
Compute md5 sums.
Compute the md5 sums of files or data, based off code from libmd
Definition in file md5.h.
Define Documentation
#define MD5_HASHBYTES 16
Definition at line 67 of file md5.h.
Referenced by MD5End().
Typedef Documentation
typedef struct MD5Context MD5_CTX
Function Documentation
char* lutil_md5_data (const unsigned char * data, unsigned int len, char * buf, GError ** err)
Compute an md5sum of the given data.
Definition at line 124 of file md5.c.
References MD5End(), MD5Init(), and MD5Update().
char* lutil_md5_file (const char * filename, char * buf, GError ** err)
Compute an md5sum of the given file.
Definition at line 96 of file md5.c.
References LUTIL_BASE_ERROR, LUTIL_BASE_ERROR_FAILED, MD5End(), MD5Init(), and MD5Update().
Referenced by luau_net_downloadUpdate().