parseupdates.h File Reference
Software repository parsing routines.
#include <glib.h>
Functions
GContainer * luau_parseXML_updates (char *contents, GError **err)
gboolean luau_parseXML_progInfo (GString *contents, AProgInfo *progInfo, GError **err)
Detailed Description
Software repository parsing routines.
Provides functionality to read in the Luau software repository file format and output a GContainer(p.) (type List) of all available software updates.
Definition in file parseupdates.h.
Function Documentation
gboolean luau_parseXML_progInfo (GString * contents, AProgInfo * progInfo, GError ** err)
Definition at line 178 of file parseupdatesxml.c.
References DBUGOUT, G_LOCK, G_UNLOCK, LUAU_BASE_ERROR, LUAU_BASE_ERROR_FAILED, luau_parseInterface(), luau_satisfiesInterface(), LUAU_XML_INTERFACE_MAJOR, LUAU_XML_INTERFACE_MINOR, AInterface::major, AInterface::minor, and parseProgInfo().
Referenced by luau_getProgInfoFromXML_data(), and luau_getProgInfoFromXML_url().
GContainer* luau_parseXML_updates (char * contents, GError ** err)
Given an Luau XML repository file in memory (ie., as a character string), read it in and parse it, returning the results (a list of updates) in a GContainer(p.) of type GCONT_LIST.
contents is a string representing a Luau XML repository file
err is a GError which will store any recoverable run-time errors
Returns: a GContainer(p.) of type GCONT_LIST of updates.
Definition at line 123 of file parseupdatesxml.c.
References DBUGOUT, g_container_new(), G_LOCK, G_UNLOCK, GCONT_LIST, LUAU_BASE_ERROR, LUAU_BASE_ERROR_FAILED, luau_parseInterface(), luau_satisfiesInterface(), LUAU_XML_INTERFACE_MAJOR, LUAU_XML_INTERFACE_MINOR, AInterface::major, AInterface::minor, parseUpdates(), and updates.
Referenced by luau_net_queryServer().