parseupdatesxml.c File Reference
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include <libxml/xmlmemory.h>
#include <libxml/parser.h>
#include <glib.h>
#include `libuau.h`
#include `util.h`
#include `error.h`
#include `parse.h`
#include `parseupdates.h`
Data Structures
struct AMirrorList
struct AMirror
struct ASetAttributes
struct ASingAttribute
struct AMultAttribute
Functions
G_LOCK_DEFINE_STATIC (parse)
void parseUpdates (xmlDocPtr doc, xmlNodePtr node)
void parseUpdate (xmlDocPtr doc, xmlNodePtr node, xmlChar *type, ASetAttributes *attributes)
void parseProgInfo (AProgInfo *progInfo, xmlDocPtr doc, xmlNodePtr node, GError **err)
void parseProgInfoTag (AProgInfo *progInfo, xmlDocPtr doc, xmlNodePtr node)
void parseMirrorList (xmlDocPtr doc, xmlNodePtr node, ASetAttributes *attributes)
void parseMirrorDef (xmlDocPtr doc, xmlNodePtr node, ASetAttributes *attributes, char *list_id)
void addToMirrorList (ASetAttributes *attributes, const char *list_id, const char *mirror_id)
void parseSoftware (xmlDocPtr doc, xmlNodePtr node, ASetAttributes *attributes)
void parsePackage (xmlDocPtr doc, xmlNodePtr node, ASetAttributes *attributes)
void parseMessage (xmlDocPtr doc, xmlNodePtr node, ASetAttributes *attributes)
void parseLibupdate (xmlDocPtr doc, xmlNodePtr node, ASetAttributes *attributes)
void parseGenericInfo (xmlDocPtr doc, xmlNodePtr node, ASetAttributes *attributes)
void parseUpdateInfo (xmlDocPtr doc, xmlNodePtr node, AUpdateType type, ASetAttributes *attributes)
void parsePkgGroup (xmlDocPtr doc, xmlNodePtr node, ASetAttributes *attributes)
GContainer * parsePackageProperties (xmlNodePtr node, APackage *pkg, ASetAttributes *attributes)
int parsePackageAttrMirrors (APackage *pkg, ASetAttributes *attributes, const char *suffix, const char *loc)
int parsePackageChildMirrors (xmlDocPtr doc, xmlNodePtr node, APackage *pkg, const char *suffix)
gboolean parseQuantData (void **data, char *str, AQuantDataType quantDataType)
AMultAttribute * appendStringToAttributeList (ASetAttributes *attributes, const char *id, const char *value)
ASingAttribute * setAttributeValue (ASetAttributes *attributes, const char *id, const char *value)
GContainer * getAttributeList (ASetAttributes *attributes, const char *id)
char * getAttributeString (ASetAttributes *attributes, const char *id)
GContainer * parseMirrorIDs (GContainer *ids, ASetAttributes *attributes)
void initializeSetAttributes (ASetAttributes *attributes)
void copySetAttributes (ASetAttributes *newSet, ASetAttributes *attributes, gboolean deepCopy)
void freeSetAttributes (ASetAttributes *attributes, gboolean deepFree)
void freeSingAttribute (ASingAttribute *attr)
void freeMultAttribute (AMultAttribute *attrs)
GContainer * luau_parseXML_updates (char *contents, GError **err)
gboolean luau_parseXML_progInfo (GString *contents, AProgInfo *progInfo, GError **err)
Variables
GContainer * updates
AUpdate * currUpdate
Function Documentation
void addToMirrorList (ASetAttributes * attributes, const char * list_id, const char * mirror_id) [static]
Definition at line 404 of file parseupdatesxml.c.
References ASetAttributes::definedMirrorLists, g_container_add(), g_container_get_iter(), g_container_new(), g_iterator_hasNext(), g_iterator_next(), GCONT_LIST, AMirrorList::id, lutil_streq(), and AMirrorList::mirrors.
Referenced by parseMirrorDef().
AMultAttribute * appendStringToAttributeList (ASetAttributes * attributes, const char * id, const char * value) [static]
Definition at line 1020 of file parseupdatesxml.c.
References g_container_add(), AMultAttribute::id, lutil_gsplit(), ASetAttributes::multAttributes, and AMultAttribute::values.
Referenced by parsePackageProperties(), and parsePkgGroup().
void copySetAttributes (ASetAttributes * newSet, ASetAttributes * attributes, gboolean deepCopy) [static]
Definition at line 1256 of file parseupdatesxml.c.
References ASetAttributes::definedMirrorLists, ASetAttributes::definedMirrors, ERROR, g_container_dup(), ASetAttributes::multAttributes, and ASetAttributes::singAttributes.
Referenced by parsePackage(), and parsePkgGroup().
void freeMultAttribute (AMultAttribute * attrs) [static]
Definition at line 1339 of file parseupdatesxml.c.
References g_container_destroy(), AMultAttribute::id, and AMultAttribute::values.
Referenced by freeSetAttributes(), and parsePkgGroup().
void freeSetAttributes (ASetAttributes * attributes, gboolean deepFree) [static]
Definition at line 1270 of file parseupdatesxml.c.
References ASetAttributes::definedMirrorLists, ASetAttributes::definedMirrors, freeMultAttribute(), freeSingAttribute(), g_container_free(), g_container_get_iter(), g_iterator_hasNext(), g_iterator_next(), ASetAttributes::multAttributes, and ASetAttributes::singAttributes.
Referenced by parsePackage(), parsePkgGroup(), and parseUpdates().
void freeSingAttribute (ASingAttribute * attr) [static]
Definition at line 1329 of file parseupdatesxml.c.
References ASingAttribute::id, and ASingAttribute::value.
Referenced by freeSetAttributes(), and parsePkgGroup().
G_LOCK_DEFINE_STATIC (parse)
GContainer * getAttributeList (ASetAttributes * attributes, const char * id) [static]
Definition at line 1102 of file parseupdatesxml.c.
References g_container_concat(), g_container_get_iter(), g_container_new(), g_iterator_hasNext(), g_iterator_next(), GCONT_LIST, AMultAttribute::id, lutil_streq(), ASetAttributes::multAttributes, and AMultAttribute::values.
Referenced by parsePackageAttrMirrors().
char * getAttributeString (ASetAttributes * attributes, const char * id) [static]
Definition at line 1152 of file parseupdatesxml.c.
References g_container_get_iter_last(), g_iterator_hasPrev(), g_iterator_prev(), ASingAttribute::id, lutil_streq(), ASetAttributes::singAttributes, and ASingAttribute::value.
Referenced by parsePackage(), and parsePackageProperties().
void initializeSetAttributes (ASetAttributes * attributes) [static]
Definition at line 1247 of file parseupdatesxml.c.
References ASetAttributes::definedMirrorLists, ASetAttributes::definedMirrors, g_container_new(), GCONT_LIST, ASetAttributes::multAttributes, and ASetAttributes::singAttributes.
Referenced by parseUpdates().
gboolean luau_parseXML_progInfo (GString * contents, AProgInfo * progInfo, GError ** err)
Definition at line 178 of file parseupdatesxml.c.
References DBUGOUT, G_LOCK, G_UNLOCK, LUAU_BASE_ERROR, LUAU_BASE_ERROR_FAILED, luau_parseInterface(), luau_satisfiesInterface(), LUAU_XML_INTERFACE_MAJOR, LUAU_XML_INTERFACE_MINOR, AInterface::major, AInterface::minor, and parseProgInfo().
Referenced by luau_getProgInfoFromXML_data(), and luau_getProgInfoFromXML_url().
GContainer* luau_parseXML_updates (char * contents, GError ** err)
Given an Luau XML repository file in memory (ie., as a character string), read it in and parse it, returning the results (a list of updates) in a GContainer(p.) of type GCONT_LIST.
contents is a string representing a Luau XML repository file
err is a GError which will store any recoverable run-time errors
Returns: a GContainer(p.) of type GCONT_LIST of updates.
Definition at line 123 of file parseupdatesxml.c.
References DBUGOUT, g_container_new(), G_LOCK, G_UNLOCK, GCONT_LIST, LUAU_BASE_ERROR, LUAU_BASE_ERROR_FAILED, luau_parseInterface(), luau_satisfiesInterface(), LUAU_XML_INTERFACE_MAJOR, LUAU_XML_INTERFACE_MINOR, AInterface::major, AInterface::minor, parseUpdates(), and updates.
Referenced by luau_net_queryServer().
void parseGenericInfo (xmlDocPtr doc, xmlNodePtr node, ASetAttributes * attributes) [static]
Definition at line 477 of file parseupdatesxml.c.
References AQuantDataType, currUpdate, AQuantifier::data, AUpdate::date, DBUGOUT, AQuantifier::dtype, AUpdate::fullDesc, AUpdate::id, AUpdate::keywords, luau_parseDate(), luau_parseQuantDataType(), LUAU_QUANT_DATA_INVALID, LUAU_QUANT_FOR, LUAU_QUANT_FROM, LUAU_QUANT_TO, lutil_parse_deleteWhitespace(), lutil_parse_parseSymbolArray(), parseQuantData(), AQuantifier::qtype, AUpdate::quantifiers, and AUpdate::shortDesc.
Referenced by parseUpdateInfo().
void parseLibupdate (xmlDocPtr doc, xmlNodePtr node, ASetAttributes * attributes) [static]
Definition at line 875 of file parseupdatesxml.c.
References currUpdate, lutil_parse_parseSymbolArray(), and AUpdate::newURL.
Referenced by parseUpdateInfo().
void parseMessage (xmlDocPtr doc, xmlNodePtr node, ASetAttributes * attributes) [static]
Definition at line 870 of file parseupdatesxml.c.
Referenced by parseUpdateInfo().
void parseMirrorDef (xmlDocPtr doc, xmlNodePtr node, ASetAttributes * attributes, char * list_id) [static]
Definition at line 371 of file parseupdatesxml.c.
References addToMirrorList(), DBUGOUT, ASetAttributes::definedMirrors, g_container_add(), ASingAttribute::id, lutil_parse_deleteWhitespace(), and ASingAttribute::value.
Referenced by parseMirrorList().
GContainer * parseMirrorIDs (GContainer * ids, ASetAttributes * attributes) [static]
Definition at line 1178 of file parseupdatesxml.c.
References DBUGOUT, ASetAttributes::definedMirrorLists, ASetAttributes::definedMirrors, g_container_add(), g_container_concat(), g_container_free(), g_container_get_iter(), g_container_new(), g_iterator_hasNext(), g_iterator_next(), GCONT_LIST, AMirrorList::id, AMirror::id, lutil_streq(), AMirrorList::mirrors, and AMirror::url.
Referenced by parsePackageAttrMirrors().
void parseMirrorList (xmlDocPtr doc, xmlNodePtr node, ASetAttributes * attributes) [static]
Definition at line 348 of file parseupdatesxml.c.
References DBUGOUT, and parseMirrorDef().
Referenced by parseUpdates().
void parsePackage (xmlDocPtr doc, xmlNodePtr node, ASetAttributes * attributes) [static]
Definition at line 611 of file parseupdatesxml.c.
References copySetAttributes(), currUpdate, DBUGOUT, freeSetAttributes(), g_container_destroy(), getAttributeString(), lutil_parse_deleteWhitespace(), APackage::mirrors, AUpdate::packages, parsePackageAttrMirrors(), parsePackageChildMirrors(), and parsePackageProperties().
Referenced by parsePkgGroup(), and parseSoftware().
int parsePackageAttrMirrors (APackage * pkg, ASetAttributes * attributes, const char * suffix, const char * loc) [static]
Definition at line 747 of file parseupdatesxml.c.
References g_container_concat(), g_container_free(), g_container_get_iter(), g_iterator_hasNext(), g_iterator_next(), getAttributeList(), GContainer::len, lutil_vstrcreate(), APackage::mirrors, and parseMirrorIDs().
Referenced by parsePackage().
int parsePackageChildMirrors (xmlDocPtr doc, xmlNodePtr node, APackage * pkg, const char * suffix) [static]
Definition at line 819 of file parseupdatesxml.c.
References DBUGOUT, lutil_parse_deleteWhitespace(), lutil_streq(), lutil_vstrcreate(), and APackage::mirrors.
Referenced by parsePackage().
GContainer * parsePackageProperties (xmlNodePtr node, APackage * pkg, ASetAttributes * attributes) [static]
Definition at line 681 of file parseupdatesxml.c.
References appendStringToAttributeList(), AUpdate::availableFormats, currUpdate, g_container_add(), g_container_concat(), g_container_new(), GCONT_LIST, getAttributeString(), AMultAttribute::id, luau_parsePkgType(), LUAU_UNKNOWN, APackage::md5sum, APackage::mirrors, APackage::size, APackage::type, AMultAttribute::values, and APackage::version.
Referenced by parsePackage().
void parsePkgGroup (xmlDocPtr doc, xmlNodePtr node, ASetAttributes * attributes) [static]
Definition at line 912 of file parseupdatesxml.c.
References appendStringToAttributeList(), copySetAttributes(), DBUGOUT, freeMultAttribute(), freeSetAttributes(), freeSingAttribute(), g_container_add(), g_container_free(), g_container_get_iter(), g_container_new(), g_iterator_hasNext(), g_iterator_next(), GCONT_LIST, lutil_parse_parseSymbolArray(), parsePackage(), and setAttributeValue().
Referenced by parseSoftware().
void parseProgInfo (AProgInfo * progInfo, xmlDocPtr doc, xmlNodePtr node, GError ** err) [static]
Definition at line 276 of file parseupdatesxml.c.
References LUAU_BASE_ERROR, LUAU_BASE_ERROR_FAILED, and parseProgInfoTag().
Referenced by luau_parseXML_progInfo().
void parseProgInfoTag (AProgInfo * progInfo, xmlDocPtr doc, xmlNodePtr node) [static]
Definition at line 294 of file parseupdatesxml.c.
References DBUGOUT, AProgInfo::desc, AProgInfo::fullname, AProgInfo::id, AProgInfo::interface, AProgInfo::keywords, lutil_parse_deleteWhitespace(), lutil_parse_parseSymbolArray(), AInterface::major, AInterface::minor, AProgInfo::shortname, and AProgInfo::url.
Referenced by parseProgInfo().
gboolean parseQuantData (void ** data, char * str, AQuantDataType quantDataType) [static]
Definition at line 891 of file parseupdatesxml.c.
References ERROR, luau_parseDate(), luau_parseInterface(), LUAU_QUANT_DATA_DATE, LUAU_QUANT_DATA_INTERFACE, LUAU_QUANT_DATA_KEYWORD, and LUAU_QUANT_DATA_VERSION.
Referenced by parseGenericInfo().
void parseSoftware (xmlDocPtr doc, xmlNodePtr node, ASetAttributes * attributes) [static]
Definition at line 575 of file parseupdatesxml.c.
References currUpdate, AUpdate::interface, luau_parseInterface(), lutil_parse_deleteWhitespace(), lutil_parse_parseSymbolArray(), AUpdate::newDisplayVersion, parsePackage(), and parsePkgGroup().
Referenced by parseUpdateInfo().
void parseUpdate (xmlDocPtr doc, xmlNodePtr node, xmlChar * type, ASetAttributes * attributes) [static]
Definition at line 438 of file parseupdatesxml.c.
References currUpdate, DBUGOUT, g_container_add(), AUpdate::keywords, LUAU_LIBUPDATE, LUAU_MESSAGE, LUAU_SOFTWARE, AUpdate::packages, parseUpdateInfo(), AUpdate::quantifiers, AUpdate::type, and updates.
Referenced by parseUpdates().
void parseUpdateInfo (xmlDocPtr doc, xmlNodePtr node, AUpdateType type, ASetAttributes * attributes) [static]
Definition at line 466 of file parseupdatesxml.c.
References LUAU_LIBUPDATE, LUAU_MESSAGE, LUAU_SOFTWARE, parseGenericInfo(), parseLibupdate(), parseMessage(), and parseSoftware().
Referenced by parseUpdate().
void parseUpdates (xmlDocPtr doc, xmlNodePtr node) [static]
Definition at line 237 of file parseupdatesxml.c.
References currUpdate, DBUGOUT, freeSetAttributes(), AUpdate::id, initializeSetAttributes(), AUpdate::newVersion, parseMirrorList(), and parseUpdate().
Referenced by luau_parseXML_updates().
ASingAttribute * setAttributeValue (ASetAttributes * attributes, const char * id, const char * value) [static]
Definition at line 1134 of file parseupdatesxml.c.
References g_container_add(), ASingAttribute::id, ASetAttributes::singAttributes, and ASingAttribute::value.
Referenced by parsePkgGroup().
Variable Documentation
AUpdate* currUpdate [static]
Definition at line 72 of file parseupdatesxml.c.
Referenced by parseGenericInfo(), parseLibupdate(), parsePackage(), parsePackageProperties(), parseSoftware(), parseUpdate(), and parseUpdates().
GContainer* updates [static]
Definition at line 71 of file parseupdatesxml.c.
Referenced by luau_parseXML_updates(), and parseUpdate().